name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore NuGet packages
      run: dotnet restore TaskAppCase4\TaskApp4.csproj
      working-directory: C:\Users\32478\Desktop\Case4TaskAppCase4
    
  


    - name: Build application
      run: |
        cd TaskAppCase4
        msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:OutDir=bin\Release\ TaskApp4.csproj
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: TaskApplication
        path: TaskAppCase4\bin\Release\