#name: Build and Release
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: windows-latest
#
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2
#
#    - name: Set up MSBuild
#      uses: microsoft/setup-msbuild@v1.0.2
#
#    - name: Restore NuGet packages
#      run: dotnet restore TaskAppCase4/TaskAppCase4.csproj
#      working-directory: TaskAppCase4
#
#    - name: Build application
#      run: |
#        msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:OutDir=bin\Release\ TaskApp4.csproj
#      working-directory: TaskAppCase4
#
#    - name: Upload artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: TaskApplication
#        path: TaskAppCase4\bin\Release\
name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: dotnet restore TaskAppCase4/TaskApp4Case4.csproj
      working-directory: C:\Users\32478\Desktop\Case4\TaskAppCase4

    - name: Build application
      run: |
        msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:OutDir=bin\Release\ TaskApp4Case4.csproj
      working-directory: C:\Users\32478\Desktop\Case4\TaskAppCase4

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: TaskApplication
        path: C:\Users\32478\Desktop\Case4\TaskAppCase4\bin\Release\
